home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('details/', views.detail, name='detail')
]

photos/urls.py
from django.contrib import admin


from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

# SETTING UP MEDIA
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from datetime import date

# Create your models here.


class Photo(models.Model):
    photo = models.ImageField(null=True)
    date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.photo)


class PhotoFolder(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=1000, null=True, blank=True)
    photos = models.ManyToManyField(Photo, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.title

    def getDateFormat(self):
        today = date.today()
        yearToday = today.strftime('%y')
        monthToday = today.strftime('%m')
        dayToday = today.strftime('%d')
        year = self.date.strftime('%y')
        month = self.date.strftime('%m')
        day = self.date.strftime('%d')

        if yearToday != year:
            return f"{month}/{day}/{year}"
        if monthToday != month:
            return f"{month}/{day}"
        if dayToday != day:
            return f"{month}/{day}"
        return self.date.strftime('%I:%M %p ')

    # def limitView(self):

    #     if len(self.photos.filter()) > 1:
    #         return [self.photos.filter()[0]]
    #     return self.photos

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import PhotoFolder
from ratelimit.decorators import ratelimit

# Create your views here.


@ratelimit(key='ip', rate='10/h', block=True)
def home(req):
    photos = PhotoFolder.objects.all().order_by('date').reverse()
    return render(req, 'home/home_index.html', {'photos': photos})


@ratelimit(key='ip', rate='10/h', block=True)
def detail(req):
    photos = PhotoFolder.objects.filter(id=req.POST.get('id'))
    return render(req, 'home/home_detail.html', {'photos': photos})

home/templates/home/baseLayout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/index.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body class="wrapper">

    {% block content %}
    {% endblock %}

</body>

</html>

home/templates/home/home_detail.html
{% extends 'home/baseLayout.html' %}

{% block title %}Detail{% endblock %}

{% block content %}
{% for photo in photos %}
<div class="eachPhotoCon">
    <p>{{photo.title}}</p>
    <p>{{photo.description}}</p>
    <p>{{photo.getDateFormat}}</p>
    <div class='imgCon imgGrid'>

        {% for img in photo.photos.filter %}
        <img src="{{img.photo.url}}" alt="photo">
        {% endfor %}
    </div>
</div>
{% endfor %}
{% endblock %}

home/templates/home/home_index.html
{% extends 'home/baseLayout.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% for photo in photos %}
<div class="eachPhotoCon">
    <p>{{photo.title}}</p>
    <p>{{photo.description}}</p>
    <p>{{photo.getDateFormat}}</p>
    <div class='imgCon imgGrid'>
        <img src="{{photo.photos.filter.0.photo.url}}" alt="photo">
        {% if photo.photos.filter|length > 1 %}
        <form method="POST" action="{% url 'home:detail' %}"> {% csrf_token %}
            <input type='hidden' name="id" value="{{photo.id}}" />
            <input type="submit" value="More" />
        </form>

        {% endif %}

        <!-- {% for img in photo.photos.filter %}
            <img src="{{img.photo.url}}" alt="photo">
            {% endfor %} -->
    </div>
</div>
{% endfor %}
{% endblock %}